[project]
name = "tachyon-mcp-search-source"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.9.4",
    "google-adk>=1.2.0",
]

[tool.adk.agents]
mcp_agent = "mcp_agent.agent:root_agent"
